using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace Pure.RelationalSchema.Abstractions.OpenAPI.Schema;

public sealed class RelationalSchemaDocumentTransformer : IOpenApiDocumentTransformer
{
    // Maps schema component names (generated by ASP.NET Core OpenAPI) to schemas matching
    // the actual JSON serialization of Pure.RelationalSchema.Abstractions types.
    private static readonly IReadOnlyDictionary<string, OpenApiSchema> RelationalSchemas =
        new Dictionary<string, OpenApiSchema>(StringComparer.Ordinal)
        {
            ["IColumn"] = new()
            {
                Type = JsonSchemaType.Object,
                Properties = new Dictionary<string, IOpenApiSchema>
                {
                    ["Name"] = new OpenApiSchema { Type = JsonSchemaType.String },
                    // IColumnType serializes as its Name string
                    ["Type"] = new OpenApiSchema { Type = JsonSchemaType.String },
                },
            },
            ["IIndex"] = new()
            {
                Type = JsonSchemaType.Object,
                Properties = new Dictionary<string, IOpenApiSchema>
                {
                    ["IsUnique"] = new OpenApiSchema { Type = JsonSchemaType.Boolean },
                    ["Columns"] = new OpenApiSchema
                    {
                        Type = JsonSchemaType.Array,
                        Items = new OpenApiSchemaReference("IColumn"),
                    },
                },
            },
            ["ITable"] = new()
            {
                Type = JsonSchemaType.Object,
                Properties = new Dictionary<string, IOpenApiSchema>
                {
                    ["Name"] = new OpenApiSchema { Type = JsonSchemaType.String },
                    ["Columns"] = new OpenApiSchema
                    {
                        Type = JsonSchemaType.Array,
                        Items = new OpenApiSchemaReference("IColumn"),
                    },
                    ["Indexes"] = new OpenApiSchema
                    {
                        Type = JsonSchemaType.Array,
                        Items = new OpenApiSchemaReference("IIndex"),
                    },
                },
            },
            ["IForeignKey"] = new()
            {
                Type = JsonSchemaType.Object,
                Properties = new Dictionary<string, IOpenApiSchema>
                {
                    ["ReferencingTable"] = new OpenApiSchemaReference("ITable"),
                    ["ReferencingColumns"] = new OpenApiSchema
                    {
                        Type = JsonSchemaType.Array,
                        Items = new OpenApiSchemaReference("IColumn"),
                    },
                    ["ReferencedTable"] = new OpenApiSchemaReference("ITable"),
                    ["ReferencedColumns"] = new OpenApiSchema
                    {
                        Type = JsonSchemaType.Array,
                        Items = new OpenApiSchemaReference("IColumn"),
                    },
                },
            },
            ["ISchema"] = new()
            {
                Type = JsonSchemaType.Object,
                Properties = new Dictionary<string, IOpenApiSchema>
                {
                    ["Name"] = new OpenApiSchema { Type = JsonSchemaType.String },
                    ["Tables"] = new OpenApiSchema
                    {
                        Type = JsonSchemaType.Array,
                        Items = new OpenApiSchemaReference("ITable"),
                    },
                    ["ForeignKeys"] = new OpenApiSchema
                    {
                        Type = JsonSchemaType.Array,
                        Items = new OpenApiSchemaReference("IForeignKey"),
                    },
                },
            },
        };

    public Task TransformAsync(
        OpenApiDocument document,
        OpenApiDocumentTransformerContext context,
        CancellationToken cancellationToken
    )
    {
        if (document.Components?.Schemas is not { } schemas)
        {
            return Task.CompletedTask;
        }

        foreach ((string name, OpenApiSchema nativeSchema) in RelationalSchemas)
        {
            if (schemas.ContainsKey(name))
            {
                schemas[name] = nativeSchema;
            }
        }

        return Task.CompletedTask;
    }
}
